/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.24.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/
export declare type PairType = {
    xyk: {};
} | {
    stable: {};
} | {
    custom: string;
};
export interface InstantiateMsg {
    fee_address?: string | null;
    generator_address?: string | null;
    owner: string;
    pair_configs: PairConfig[];
    token_code_id: number;
    whitelist_code_id: number;
}
export interface PairConfig {
    code_id: number;
    is_disabled: boolean;
    is_generator_disabled: boolean;
    maker_fee_bps: number;
    pair_type: PairType;
    total_fee_bps: number;
}
export declare type ExecuteMsg = {
    update_config: {
        fee_address?: string | null;
        generator_address?: string | null;
        token_code_id?: number | null;
        whitelist_code_id?: number | null;
    };
} | {
    update_pair_config: {
        config: PairConfig;
    };
} | {
    create_pair: {
        asset_infos: AssetInfo[];
        init_params?: Binary | null;
        pair_type: PairType;
    };
} | {
    deregister: {
        asset_infos: AssetInfo[];
    };
} | {
    propose_new_owner: {
        expires_in: number;
        owner: string;
    };
} | {
    drop_ownership_proposal: {};
} | {
    claim_ownership: {};
} | {
    mark_as_migrated: {
        pairs: string[];
    };
};
export declare type AssetInfo = {
    token: {
        contract_addr: Addr;
    };
} | {
    native_token: {
        denom: string;
    };
};
export declare type Addr = string;
export declare type Binary = string;
export declare type QueryMsg = {
    config: {};
} | {
    pair: {
        asset_infos: AssetInfo[];
    };
} | {
    pairs: {
        limit?: number | null;
        start_after?: AssetInfo[] | null;
    };
} | {
    fee_info: {
        pair_type: PairType;
    };
} | {
    blacklisted_pair_types: {};
} | {
    pairs_to_migrate: {};
};
export interface MigrateMsg {
    params: Binary;
}
export declare type ArrayOfPairType = PairType[];
export interface ConfigResponse {
    fee_address?: Addr | null;
    generator_address?: Addr | null;
    owner: Addr;
    pair_configs: PairConfig[];
    token_code_id: number;
    whitelist_code_id: number;
}
export interface FeeInfoResponse {
    fee_address?: Addr | null;
    maker_fee_bps: number;
    total_fee_bps: number;
}
export interface PairInfo {
    asset_infos: AssetInfo[];
    contract_addr: Addr;
    liquidity_token: Addr;
    pair_type: PairType;
}
export interface PairsResponse {
    pairs: PairInfo[];
}
export declare type ArrayOfAddr = Addr[];
