/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.24.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/
export declare type AssetInfo = {
    token: {
        contract_addr: Addr;
    };
} | {
    native_token: {
        denom: string;
    };
};
export declare type Addr = string;
export interface InstantiateMsg {
    asset_infos: AssetInfo[];
    factory_contract: string;
}
export declare type ExecuteMsg = {
    update: {};
};
export declare type QueryMsg = {
    consult: {
        amount: Uint128;
        token: AssetInfo;
    };
};
export declare type Uint128 = string;
export interface MigrateMsg {
}
export declare type Uint256 = string;
export declare type ArrayOfTupleOfAssetInfoAndUint256 = [AssetInfo, Uint256][];
