/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.24.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/
import { MsgExecuteContractEncodeObject } from "cosmwasm";
import { CosmosMsgForEmpty, Coin } from "./AstroportWhitelist.types";
export interface AstroportWhitelistMessage {
    contractAddress: string;
    sender: string;
    execute: ({ msgs }: {
        msgs: CosmosMsgForEmpty[];
    }, funds?: Coin[]) => MsgExecuteContractEncodeObject;
    freeze: (funds?: Coin[]) => MsgExecuteContractEncodeObject;
    updateAdmins: ({ admins }: {
        admins: string[];
    }, funds?: Coin[]) => MsgExecuteContractEncodeObject;
}
export declare class AstroportWhitelistMessageComposer implements AstroportWhitelistMessage {
    sender: string;
    contractAddress: string;
    constructor(sender: string, contractAddress: string);
    execute: ({ msgs }: {
        msgs: CosmosMsgForEmpty[];
    }, funds?: Coin[]) => MsgExecuteContractEncodeObject;
    freeze: (funds?: Coin[]) => MsgExecuteContractEncodeObject;
    updateAdmins: ({ admins }: {
        admins: string[];
    }, funds?: Coin[]) => MsgExecuteContractEncodeObject;
}
