/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.24.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/
export interface InstantiateMsg {
    owner: string;
    token_addr: string;
}
export declare type ExecuteMsg = {
    claim: {
        amount?: Uint128 | null;
        recipient?: string | null;
    };
} | {
    receive: Cw20ReceiveMsg;
} | {
    propose_new_owner: {
        expires_in: number;
        owner: string;
    };
} | {
    drop_ownership_proposal: {};
} | {
    claim_ownership: {};
};
export declare type Uint128 = string;
export declare type Binary = string;
export interface Cw20ReceiveMsg {
    amount: Uint128;
    msg: Binary;
    sender: string;
}
export declare type QueryMsg = {
    config: {};
} | {
    vesting_account: {
        address: string;
    };
} | {
    vesting_accounts: {
        limit?: number | null;
        order_by?: OrderBy | null;
        start_after?: string | null;
    };
} | {
    available_amount: {
        address: string;
    };
} | {
    timestamp: {};
};
export declare type OrderBy = "asc" | "desc";
export interface MigrateMsg {
}
export declare type Addr = string;
export interface ConfigResponse {
    owner: Addr;
    token_addr: Addr;
}
export declare type Uint64 = number;
export interface VestingAccountResponse {
    address: Addr;
    info: VestingInfo;
}
export interface VestingInfo {
    released_amount: Uint128;
    schedules: VestingSchedule[];
}
export interface VestingSchedule {
    end_point?: VestingSchedulePoint | null;
    start_point: VestingSchedulePoint;
}
export interface VestingSchedulePoint {
    amount: Uint128;
    time: number;
}
export interface VestingAccountsResponse {
    vesting_accounts: VestingAccountResponse[];
}
