/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.24.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/
import { CosmWasmClient, SigningCosmWasmClient, ExecuteResult } from "@cosmjs/cosmwasm-stargate";
import { Coin, StdFee } from "@cosmjs/amino";
import { AssetInfo, Addr, Binary, Uint128, Decimal, Asset, ConfigResponse, CumulativePricesResponse, PairInfo, PoolResponse, ReverseSimulationResponse, ArrayOfAsset, SimulationResponse } from "./AstroportPairAstroXastro.types";
export interface AstroportPairAstroXastroReadOnlyInterface {
    contractAddress: string;
    pair: () => Promise<PairInfo>;
    pool: () => Promise<PoolResponse>;
    config: () => Promise<ConfigResponse>;
    share: ({ amount }: {
        amount: Uint128;
    }) => Promise<ArrayOfAsset>;
    simulation: ({ offerAsset }: {
        offerAsset: Asset;
    }) => Promise<SimulationResponse>;
    reverseSimulation: ({ askAsset }: {
        askAsset: Asset;
    }) => Promise<ReverseSimulationResponse>;
    cumulativePrices: () => Promise<CumulativePricesResponse>;
}
export declare class AstroportPairAstroXastroQueryClient implements AstroportPairAstroXastroReadOnlyInterface {
    client: CosmWasmClient;
    contractAddress: string;
    constructor(client: CosmWasmClient, contractAddress: string);
    pair: () => Promise<PairInfo>;
    pool: () => Promise<PoolResponse>;
    config: () => Promise<ConfigResponse>;
    share: ({ amount }: {
        amount: Uint128;
    }) => Promise<ArrayOfAsset>;
    simulation: ({ offerAsset }: {
        offerAsset: Asset;
    }) => Promise<SimulationResponse>;
    reverseSimulation: ({ askAsset }: {
        askAsset: Asset;
    }) => Promise<ReverseSimulationResponse>;
    cumulativePrices: () => Promise<CumulativePricesResponse>;
}
export interface AstroportPairAstroXastroInterface extends AstroportPairAstroXastroReadOnlyInterface {
    contractAddress: string;
    sender: string;
    receive: ({ amount, msg, sender }: {
        amount: Uint128;
        msg: Binary;
        sender: string;
    }, fee?: number | StdFee | "auto", memo?: string, funds?: Coin[]) => Promise<ExecuteResult>;
    provideLiquidity: ({ assets, autoStake, receiver, slippageTolerance }: {
        assets: Asset[];
        autoStake?: boolean;
        receiver?: string;
        slippageTolerance?: Decimal;
    }, fee?: number | StdFee | "auto", memo?: string, funds?: Coin[]) => Promise<ExecuteResult>;
    swap: ({ beliefPrice, maxSpread, offerAsset, to }: {
        beliefPrice?: Decimal;
        maxSpread?: Decimal;
        offerAsset: Asset;
        to?: string;
    }, fee?: number | StdFee | "auto", memo?: string, funds?: Coin[]) => Promise<ExecuteResult>;
    updateConfig: ({ params }: {
        params: Binary;
    }, fee?: number | StdFee | "auto", memo?: string, funds?: Coin[]) => Promise<ExecuteResult>;
    assertAndSend: ({ askAssetInfo, offerAsset, receiver, sender }: {
        askAssetInfo: AssetInfo;
        offerAsset: Asset;
        receiver: Addr;
        sender: Addr;
    }, fee?: number | StdFee | "auto", memo?: string, funds?: Coin[]) => Promise<ExecuteResult>;
}
export declare class AstroportPairAstroXastroClient extends AstroportPairAstroXastroQueryClient implements AstroportPairAstroXastroInterface {
    client: SigningCosmWasmClient;
    sender: string;
    contractAddress: string;
    constructor(client: SigningCosmWasmClient, sender: string, contractAddress: string);
    receive: ({ amount, msg, sender }: {
        amount: Uint128;
        msg: Binary;
        sender: string;
    }, fee?: number | StdFee | "auto", memo?: string, funds?: Coin[]) => Promise<ExecuteResult>;
    provideLiquidity: ({ assets, autoStake, receiver, slippageTolerance }: {
        assets: Asset[];
        autoStake?: boolean | undefined;
        receiver?: string | undefined;
        slippageTolerance?: string | undefined;
    }, fee?: number | StdFee | "auto", memo?: string, funds?: Coin[]) => Promise<ExecuteResult>;
    swap: ({ beliefPrice, maxSpread, offerAsset, to }: {
        beliefPrice?: string | undefined;
        maxSpread?: string | undefined;
        offerAsset: Asset;
        to?: string | undefined;
    }, fee?: number | StdFee | "auto", memo?: string, funds?: Coin[]) => Promise<ExecuteResult>;
    updateConfig: ({ params }: {
        params: Binary;
    }, fee?: number | StdFee | "auto", memo?: string, funds?: Coin[]) => Promise<ExecuteResult>;
    assertAndSend: ({ askAssetInfo, offerAsset, receiver, sender }: {
        askAssetInfo: AssetInfo;
        offerAsset: Asset;
        receiver: Addr;
        sender: Addr;
    }, fee?: number | StdFee | "auto", memo?: string, funds?: Coin[]) => Promise<ExecuteResult>;
}
