/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.24.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/
import { CosmWasmClient, SigningCosmWasmClient, ExecuteResult } from "@cosmjs/cosmwasm-stargate";
import { StdFee } from "@cosmjs/amino";
import { CosmosMsgForEmpty, Coin, AdminListResponse, CanExecuteResponse } from "./AstroportWhitelist.types";
export interface AstroportWhitelistReadOnlyInterface {
    contractAddress: string;
    adminList: () => Promise<AdminListResponse>;
    canExecute: ({ msg, sender }: {
        msg: CosmosMsgForEmpty;
        sender: string;
    }) => Promise<CanExecuteResponse>;
}
export declare class AstroportWhitelistQueryClient implements AstroportWhitelistReadOnlyInterface {
    client: CosmWasmClient;
    contractAddress: string;
    constructor(client: CosmWasmClient, contractAddress: string);
    adminList: () => Promise<AdminListResponse>;
    canExecute: ({ msg, sender }: {
        msg: CosmosMsgForEmpty;
        sender: string;
    }) => Promise<CanExecuteResponse>;
}
export interface AstroportWhitelistInterface extends AstroportWhitelistReadOnlyInterface {
    contractAddress: string;
    sender: string;
    execute: ({ msgs }: {
        msgs: CosmosMsgForEmpty[];
    }, fee?: number | StdFee | "auto", memo?: string, funds?: Coin[]) => Promise<ExecuteResult>;
    freeze: (fee?: number | StdFee | "auto", memo?: string, funds?: Coin[]) => Promise<ExecuteResult>;
    updateAdmins: ({ admins }: {
        admins: string[];
    }, fee?: number | StdFee | "auto", memo?: string, funds?: Coin[]) => Promise<ExecuteResult>;
}
export declare class AstroportWhitelistClient extends AstroportWhitelistQueryClient implements AstroportWhitelistInterface {
    client: SigningCosmWasmClient;
    sender: string;
    contractAddress: string;
    constructor(client: SigningCosmWasmClient, sender: string, contractAddress: string);
    execute: ({ msgs }: {
        msgs: CosmosMsgForEmpty[];
    }, fee?: number | StdFee | "auto", memo?: string, funds?: Coin[]) => Promise<ExecuteResult>;
    freeze: (fee?: number | StdFee | "auto", memo?: string, funds?: Coin[]) => Promise<ExecuteResult>;
    updateAdmins: ({ admins }: {
        admins: string[];
    }, fee?: number | StdFee | "auto", memo?: string, funds?: Coin[]) => Promise<ExecuteResult>;
}
