/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.24.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/
export declare type Logo = {
    url: string;
} | {
    embedded: EmbeddedLogo;
};
export declare type EmbeddedLogo = {
    svg: Binary;
} | {
    png: Binary;
};
export declare type Binary = string;
export interface InstantiateMsg {
    deposit_token_addr: string;
    marketing?: InstantiateMarketingInfo | null;
    owner: string;
    token_code_id: number;
}
export interface InstantiateMarketingInfo {
    description?: string | null;
    logo?: Logo | null;
    marketing?: string | null;
    project?: string | null;
}
export declare type ExecuteMsg = {
    receive: Cw20ReceiveMsg;
};
export declare type Uint128 = string;
export interface Cw20ReceiveMsg {
    amount: Uint128;
    msg: Binary;
    sender: string;
}
export declare type QueryMsg = {
    config: {};
} | {
    total_shares: {};
} | {
    total_deposit: {};
};
export interface MigrateMsg {
}
export declare type Addr = string;
export interface ConfigResponse {
    deposit_token_addr: Addr;
    share_token_addr: Addr;
}
