/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.24.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/
import { CosmWasmClient, SigningCosmWasmClient, ExecuteResult } from "@cosmjs/cosmwasm-stargate";
import { Coin, StdFee } from "@cosmjs/amino";
import { PairType, PairConfig, AssetInfo, Binary, ArrayOfPairType, ConfigResponse, FeeInfoResponse, PairInfo, PairsResponse, ArrayOfAddr } from "./AstroportFactory.types";
export interface AstroportFactoryReadOnlyInterface {
    contractAddress: string;
    config: () => Promise<ConfigResponse>;
    pair: ({ assetInfos }: {
        assetInfos: AssetInfo[];
    }) => Promise<PairInfo>;
    pairs: ({ limit, startAfter }: {
        limit?: number;
        startAfter?: AssetInfo[];
    }) => Promise<PairsResponse>;
    feeInfo: ({ pairType }: {
        pairType: PairType;
    }) => Promise<FeeInfoResponse>;
    blacklistedPairTypes: () => Promise<ArrayOfPairType>;
    pairsToMigrate: () => Promise<ArrayOfAddr>;
}
export declare class AstroportFactoryQueryClient implements AstroportFactoryReadOnlyInterface {
    client: CosmWasmClient;
    contractAddress: string;
    constructor(client: CosmWasmClient, contractAddress: string);
    config: () => Promise<ConfigResponse>;
    pair: ({ assetInfos }: {
        assetInfos: AssetInfo[];
    }) => Promise<PairInfo>;
    pairs: ({ limit, startAfter }: {
        limit?: number | undefined;
        startAfter?: AssetInfo[] | undefined;
    }) => Promise<PairsResponse>;
    feeInfo: ({ pairType }: {
        pairType: PairType;
    }) => Promise<FeeInfoResponse>;
    blacklistedPairTypes: () => Promise<ArrayOfPairType>;
    pairsToMigrate: () => Promise<ArrayOfAddr>;
}
export interface AstroportFactoryInterface extends AstroportFactoryReadOnlyInterface {
    contractAddress: string;
    sender: string;
    updateConfig: ({ feeAddress, generatorAddress, tokenCodeId, whitelistCodeId }: {
        feeAddress?: string;
        generatorAddress?: string;
        tokenCodeId?: number;
        whitelistCodeId?: number;
    }, fee?: number | StdFee | "auto", memo?: string, funds?: Coin[]) => Promise<ExecuteResult>;
    updatePairConfig: ({ config }: {
        config: PairConfig;
    }, fee?: number | StdFee | "auto", memo?: string, funds?: Coin[]) => Promise<ExecuteResult>;
    createPair: ({ assetInfos, initParams, pairType }: {
        assetInfos: AssetInfo[];
        initParams?: Binary;
        pairType: PairType;
    }, fee?: number | StdFee | "auto", memo?: string, funds?: Coin[]) => Promise<ExecuteResult>;
    deregister: ({ assetInfos }: {
        assetInfos: AssetInfo[];
    }, fee?: number | StdFee | "auto", memo?: string, funds?: Coin[]) => Promise<ExecuteResult>;
    proposeNewOwner: ({ expiresIn, owner }: {
        expiresIn: number;
        owner: string;
    }, fee?: number | StdFee | "auto", memo?: string, funds?: Coin[]) => Promise<ExecuteResult>;
    dropOwnershipProposal: (fee?: number | StdFee | "auto", memo?: string, funds?: Coin[]) => Promise<ExecuteResult>;
    claimOwnership: (fee?: number | StdFee | "auto", memo?: string, funds?: Coin[]) => Promise<ExecuteResult>;
    markAsMigrated: ({ pairs }: {
        pairs: string[];
    }, fee?: number | StdFee | "auto", memo?: string, funds?: Coin[]) => Promise<ExecuteResult>;
}
export declare class AstroportFactoryClient extends AstroportFactoryQueryClient implements AstroportFactoryInterface {
    client: SigningCosmWasmClient;
    sender: string;
    contractAddress: string;
    constructor(client: SigningCosmWasmClient, sender: string, contractAddress: string);
    updateConfig: ({ feeAddress, generatorAddress, tokenCodeId, whitelistCodeId }: {
        feeAddress?: string | undefined;
        generatorAddress?: string | undefined;
        tokenCodeId?: number | undefined;
        whitelistCodeId?: number | undefined;
    }, fee?: number | StdFee | "auto", memo?: string, funds?: Coin[]) => Promise<ExecuteResult>;
    updatePairConfig: ({ config }: {
        config: PairConfig;
    }, fee?: number | StdFee | "auto", memo?: string, funds?: Coin[]) => Promise<ExecuteResult>;
    createPair: ({ assetInfos, initParams, pairType }: {
        assetInfos: AssetInfo[];
        initParams?: string | undefined;
        pairType: PairType;
    }, fee?: number | StdFee | "auto", memo?: string, funds?: Coin[]) => Promise<ExecuteResult>;
    deregister: ({ assetInfos }: {
        assetInfos: AssetInfo[];
    }, fee?: number | StdFee | "auto", memo?: string, funds?: Coin[]) => Promise<ExecuteResult>;
    proposeNewOwner: ({ expiresIn, owner }: {
        expiresIn: number;
        owner: string;
    }, fee?: number | StdFee | "auto", memo?: string, funds?: Coin[]) => Promise<ExecuteResult>;
    dropOwnershipProposal: (fee?: number | StdFee | "auto", memo?: string, funds?: Coin[]) => Promise<ExecuteResult>;
    claimOwnership: (fee?: number | StdFee | "auto", memo?: string, funds?: Coin[]) => Promise<ExecuteResult>;
    markAsMigrated: ({ pairs }: {
        pairs: string[];
    }, fee?: number | StdFee | "auto", memo?: string, funds?: Coin[]) => Promise<ExecuteResult>;
}
