"use strict";
/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.24.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/
var __extends = (this && this.__extends) || (function () {
    var extendStatics = function (d, b) {
        extendStatics = Object.setPrototypeOf ||
            ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
            function (d, b) { for (var p in b) if (Object.prototype.hasOwnProperty.call(b, p)) d[p] = b[p]; };
        return extendStatics(d, b);
    };
    return function (d, b) {
        if (typeof b !== "function" && b !== null)
            throw new TypeError("Class extends value " + String(b) + " is not a constructor or null");
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
    function adopt(value) { return value instanceof P ? value : new P(function (resolve) { resolve(value); }); }
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : adopt(result.value).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
};
var __generator = (this && this.__generator) || function (thisArg, body) {
    var _ = { label: 0, sent: function() { if (t[0] & 1) throw t[1]; return t[1]; }, trys: [], ops: [] }, f, y, t, g;
    return g = { next: verb(0), "throw": verb(1), "return": verb(2) }, typeof Symbol === "function" && (g[Symbol.iterator] = function() { return this; }), g;
    function verb(n) { return function (v) { return step([n, v]); }; }
    function step(op) {
        if (f) throw new TypeError("Generator is already executing.");
        while (_) try {
            if (f = 1, y && (t = op[0] & 2 ? y["return"] : op[0] ? y["throw"] || ((t = y["return"]) && t.call(y), 0) : y.next) && !(t = t.call(y, op[1])).done) return t;
            if (y = 0, t) op = [op[0] & 2, t.value];
            switch (op[0]) {
                case 0: case 1: t = op; break;
                case 4: _.label++; return { value: op[1], done: false };
                case 5: _.label++; y = op[1]; op = [0]; continue;
                case 7: op = _.ops.pop(); _.trys.pop(); continue;
                default:
                    if (!(t = _.trys, t = t.length > 0 && t[t.length - 1]) && (op[0] === 6 || op[0] === 2)) { _ = 0; continue; }
                    if (op[0] === 3 && (!t || (op[1] > t[0] && op[1] < t[3]))) { _.label = op[1]; break; }
                    if (op[0] === 6 && _.label < t[1]) { _.label = t[1]; t = op; break; }
                    if (t && _.label < t[2]) { _.label = t[2]; _.ops.push(op); break; }
                    if (t[2]) _.ops.pop();
                    _.trys.pop(); continue;
            }
            op = body.call(thisArg, _);
        } catch (e) { op = [6, e]; y = 0; } finally { f = t = 0; }
        if (op[0] & 5) throw op[1]; return { value: op[0] ? op[1] : void 0, done: true };
    }
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.AstroportFactoryClient = exports.AstroportFactoryQueryClient = void 0;
var AstroportFactoryQueryClient = /** @class */ (function () {
    function AstroportFactoryQueryClient(client, contractAddress) {
        var _this = this;
        this.config = function () { return __awaiter(_this, void 0, void 0, function () {
            return __generator(this, function (_a) {
                return [2 /*return*/, this.client.queryContractSmart(this.contractAddress, {
                        config: {}
                    })];
            });
        }); };
        this.pair = function (_a) {
            var assetInfos = _a.assetInfos;
            return __awaiter(_this, void 0, void 0, function () {
                return __generator(this, function (_b) {
                    return [2 /*return*/, this.client.queryContractSmart(this.contractAddress, {
                            pair: {
                                asset_infos: assetInfos
                            }
                        })];
                });
            });
        };
        this.pairs = function (_a) {
            var limit = _a.limit, startAfter = _a.startAfter;
            return __awaiter(_this, void 0, void 0, function () {
                return __generator(this, function (_b) {
                    return [2 /*return*/, this.client.queryContractSmart(this.contractAddress, {
                            pairs: {
                                limit: limit,
                                start_after: startAfter
                            }
                        })];
                });
            });
        };
        this.feeInfo = function (_a) {
            var pairType = _a.pairType;
            return __awaiter(_this, void 0, void 0, function () {
                return __generator(this, function (_b) {
                    return [2 /*return*/, this.client.queryContractSmart(this.contractAddress, {
                            fee_info: {
                                pair_type: pairType
                            }
                        })];
                });
            });
        };
        this.blacklistedPairTypes = function () { return __awaiter(_this, void 0, void 0, function () {
            return __generator(this, function (_a) {
                return [2 /*return*/, this.client.queryContractSmart(this.contractAddress, {
                        blacklisted_pair_types: {}
                    })];
            });
        }); };
        this.pairsToMigrate = function () { return __awaiter(_this, void 0, void 0, function () {
            return __generator(this, function (_a) {
                return [2 /*return*/, this.client.queryContractSmart(this.contractAddress, {
                        pairs_to_migrate: {}
                    })];
            });
        }); };
        this.client = client;
        this.contractAddress = contractAddress;
        this.config = this.config.bind(this);
        this.pair = this.pair.bind(this);
        this.pairs = this.pairs.bind(this);
        this.feeInfo = this.feeInfo.bind(this);
        this.blacklistedPairTypes = this.blacklistedPairTypes.bind(this);
        this.pairsToMigrate = this.pairsToMigrate.bind(this);
    }
    return AstroportFactoryQueryClient;
}());
exports.AstroportFactoryQueryClient = AstroportFactoryQueryClient;
var AstroportFactoryClient = /** @class */ (function (_super) {
    __extends(AstroportFactoryClient, _super);
    function AstroportFactoryClient(client, sender, contractAddress) {
        var _this = _super.call(this, client, contractAddress) || this;
        _this.updateConfig = function (_a, fee, memo, funds) {
            var feeAddress = _a.feeAddress, generatorAddress = _a.generatorAddress, tokenCodeId = _a.tokenCodeId, whitelistCodeId = _a.whitelistCodeId;
            if (fee === void 0) { fee = "auto"; }
            return __awaiter(_this, void 0, void 0, function () {
                return __generator(this, function (_b) {
                    switch (_b.label) {
                        case 0: return [4 /*yield*/, this.client.execute(this.sender, this.contractAddress, {
                                update_config: {
                                    fee_address: feeAddress,
                                    generator_address: generatorAddress,
                                    token_code_id: tokenCodeId,
                                    whitelist_code_id: whitelistCodeId
                                }
                            }, fee, memo, funds)];
                        case 1: return [2 /*return*/, _b.sent()];
                    }
                });
            });
        };
        _this.updatePairConfig = function (_a, fee, memo, funds) {
            var config = _a.config;
            if (fee === void 0) { fee = "auto"; }
            return __awaiter(_this, void 0, void 0, function () {
                return __generator(this, function (_b) {
                    switch (_b.label) {
                        case 0: return [4 /*yield*/, this.client.execute(this.sender, this.contractAddress, {
                                update_pair_config: {
                                    config: config
                                }
                            }, fee, memo, funds)];
                        case 1: return [2 /*return*/, _b.sent()];
                    }
                });
            });
        };
        _this.createPair = function (_a, fee, memo, funds) {
            var assetInfos = _a.assetInfos, initParams = _a.initParams, pairType = _a.pairType;
            if (fee === void 0) { fee = "auto"; }
            return __awaiter(_this, void 0, void 0, function () {
                return __generator(this, function (_b) {
                    switch (_b.label) {
                        case 0: return [4 /*yield*/, this.client.execute(this.sender, this.contractAddress, {
                                create_pair: {
                                    asset_infos: assetInfos,
                                    init_params: initParams,
                                    pair_type: pairType
                                }
                            }, fee, memo, funds)];
                        case 1: return [2 /*return*/, _b.sent()];
                    }
                });
            });
        };
        _this.deregister = function (_a, fee, memo, funds) {
            var assetInfos = _a.assetInfos;
            if (fee === void 0) { fee = "auto"; }
            return __awaiter(_this, void 0, void 0, function () {
                return __generator(this, function (_b) {
                    switch (_b.label) {
                        case 0: return [4 /*yield*/, this.client.execute(this.sender, this.contractAddress, {
                                deregister: {
                                    asset_infos: assetInfos
                                }
                            }, fee, memo, funds)];
                        case 1: return [2 /*return*/, _b.sent()];
                    }
                });
            });
        };
        _this.proposeNewOwner = function (_a, fee, memo, funds) {
            var expiresIn = _a.expiresIn, owner = _a.owner;
            if (fee === void 0) { fee = "auto"; }
            return __awaiter(_this, void 0, void 0, function () {
                return __generator(this, function (_b) {
                    switch (_b.label) {
                        case 0: return [4 /*yield*/, this.client.execute(this.sender, this.contractAddress, {
                                propose_new_owner: {
                                    expires_in: expiresIn,
                                    owner: owner
                                }
                            }, fee, memo, funds)];
                        case 1: return [2 /*return*/, _b.sent()];
                    }
                });
            });
        };
        _this.dropOwnershipProposal = function (fee, memo, funds) {
            if (fee === void 0) { fee = "auto"; }
            return __awaiter(_this, void 0, void 0, function () {
                return __generator(this, function (_a) {
                    switch (_a.label) {
                        case 0: return [4 /*yield*/, this.client.execute(this.sender, this.contractAddress, {
                                drop_ownership_proposal: {}
                            }, fee, memo, funds)];
                        case 1: return [2 /*return*/, _a.sent()];
                    }
                });
            });
        };
        _this.claimOwnership = function (fee, memo, funds) {
            if (fee === void 0) { fee = "auto"; }
            return __awaiter(_this, void 0, void 0, function () {
                return __generator(this, function (_a) {
                    switch (_a.label) {
                        case 0: return [4 /*yield*/, this.client.execute(this.sender, this.contractAddress, {
                                claim_ownership: {}
                            }, fee, memo, funds)];
                        case 1: return [2 /*return*/, _a.sent()];
                    }
                });
            });
        };
        _this.markAsMigrated = function (_a, fee, memo, funds) {
            var pairs = _a.pairs;
            if (fee === void 0) { fee = "auto"; }
            return __awaiter(_this, void 0, void 0, function () {
                return __generator(this, function (_b) {
                    switch (_b.label) {
                        case 0: return [4 /*yield*/, this.client.execute(this.sender, this.contractAddress, {
                                mark_as_migrated: {
                                    pairs: pairs
                                }
                            }, fee, memo, funds)];
                        case 1: return [2 /*return*/, _b.sent()];
                    }
                });
            });
        };
        _this.client = client;
        _this.sender = sender;
        _this.contractAddress = contractAddress;
        _this.updateConfig = _this.updateConfig.bind(_this);
        _this.updatePairConfig = _this.updatePairConfig.bind(_this);
        _this.createPair = _this.createPair.bind(_this);
        _this.deregister = _this.deregister.bind(_this);
        _this.proposeNewOwner = _this.proposeNewOwner.bind(_this);
        _this.dropOwnershipProposal = _this.dropOwnershipProposal.bind(_this);
        _this.claimOwnership = _this.claimOwnership.bind(_this);
        _this.markAsMigrated = _this.markAsMigrated.bind(_this);
        return _this;
    }
    return AstroportFactoryClient;
}(AstroportFactoryQueryClient));
exports.AstroportFactoryClient = AstroportFactoryClient;
