/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.24.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/
import { CosmWasmClient, SigningCosmWasmClient, ExecuteResult } from "@cosmjs/cosmwasm-stargate";
import { Coin, StdFee } from "@cosmjs/amino";
import { AssetInfo, Uint128, ArrayOfTupleOfAssetInfoAndUint256 } from "./AstroportOracle.types";
export interface AstroportOracleReadOnlyInterface {
    contractAddress: string;
    consult: ({ amount, token }: {
        amount: Uint128;
        token: AssetInfo;
    }) => Promise<ArrayOfTupleOfAssetInfoAndUint256>;
}
export declare class AstroportOracleQueryClient implements AstroportOracleReadOnlyInterface {
    client: CosmWasmClient;
    contractAddress: string;
    constructor(client: CosmWasmClient, contractAddress: string);
    consult: ({ amount, token }: {
        amount: Uint128;
        token: AssetInfo;
    }) => Promise<ArrayOfTupleOfAssetInfoAndUint256>;
}
export interface AstroportOracleInterface extends AstroportOracleReadOnlyInterface {
    contractAddress: string;
    sender: string;
    update: (fee?: number | StdFee | "auto", memo?: string, funds?: Coin[]) => Promise<ExecuteResult>;
}
export declare class AstroportOracleClient extends AstroportOracleQueryClient implements AstroportOracleInterface {
    client: SigningCosmWasmClient;
    sender: string;
    contractAddress: string;
    constructor(client: SigningCosmWasmClient, sender: string, contractAddress: string);
    update: (fee?: number | StdFee | "auto", memo?: string, funds?: Coin[]) => Promise<ExecuteResult>;
}
