"use strict";
/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.24.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/
var __assign = (this && this.__assign) || function () {
    __assign = Object.assign || function(t) {
        for (var s, i = 1, n = arguments.length; i < n; i++) {
            s = arguments[i];
            for (var p in s) if (Object.prototype.hasOwnProperty.call(s, p))
                t[p] = s[p];
        }
        return t;
    };
    return __assign.apply(this, arguments);
};
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (k !== "default" && Object.prototype.hasOwnProperty.call(mod, k)) __createBinding(result, mod, k);
    __setModuleDefault(result, mod);
    return result;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.contracts = void 0;
var _0 = __importStar(require("./AstroportFactory.types"));
var _1 = __importStar(require("./AstroportFactory.client"));
var _2 = __importStar(require("./AstroportFactory.message-composer"));
var _3 = __importStar(require("./AstroportPair.types"));
var _4 = __importStar(require("./AstroportPair.client"));
var _5 = __importStar(require("./AstroportPair.message-composer"));
var _6 = __importStar(require("./AstroportToken.types"));
var _7 = __importStar(require("./AstroportToken.client"));
var _8 = __importStar(require("./AstroportToken.message-composer"));
var _9 = __importStar(require("./AstroportPairStable.types"));
var _10 = __importStar(require("./AstroportPairStable.client"));
var _11 = __importStar(require("./AstroportPairStable.message-composer"));
var _12 = __importStar(require("./AstroportPairAstroXastro.types"));
var _13 = __importStar(require("./AstroportPairAstroXastro.client"));
var _14 = __importStar(require("./AstroportPairAstroXastro.message-composer"));
var _15 = __importStar(require("./AstroportStaking.types"));
var _16 = __importStar(require("./AstroportStaking.client"));
var _17 = __importStar(require("./AstroportStaking.message-composer"));
var _18 = __importStar(require("./AstroportXastroToken.types"));
var _19 = __importStar(require("./AstroportXastroToken.client"));
var _20 = __importStar(require("./AstroportXastroToken.message-composer"));
var _21 = __importStar(require("./AstroportRouter.types"));
var _22 = __importStar(require("./AstroportRouter.client"));
var _23 = __importStar(require("./AstroportRouter.message-composer"));
var _24 = __importStar(require("./AstroportWhitelist.types"));
var _25 = __importStar(require("./AstroportWhitelist.client"));
var _26 = __importStar(require("./AstroportWhitelist.message-composer"));
var _27 = __importStar(require("./AstroportGenerator.types"));
var _28 = __importStar(require("./AstroportGenerator.client"));
var _29 = __importStar(require("./AstroportGenerator.message-composer"));
var _30 = __importStar(require("./AstroportVesting.types"));
var _31 = __importStar(require("./AstroportVesting.client"));
var _32 = __importStar(require("./AstroportVesting.message-composer"));
var _33 = __importStar(require("./AstroportMaker.types"));
var _34 = __importStar(require("./AstroportMaker.client"));
var _35 = __importStar(require("./AstroportMaker.message-composer"));
var _36 = __importStar(require("./AstroportOracle.types"));
var _37 = __importStar(require("./AstroportOracle.client"));
var _38 = __importStar(require("./AstroportOracle.message-composer"));
var contracts;
(function (contracts) {
    contracts.AstroportFactory = __assign(__assign(__assign({}, _0), _1), _2);
    contracts.AstroportPair = __assign(__assign(__assign({}, _3), _4), _5);
    contracts.AstroportToken = __assign(__assign(__assign({}, _6), _7), _8);
    contracts.AstroportPairStable = __assign(__assign(__assign({}, _9), _10), _11);
    contracts.AstroportPairAstroXastro = __assign(__assign(__assign({}, _12), _13), _14);
    contracts.AstroportStaking = __assign(__assign(__assign({}, _15), _16), _17);
    contracts.AstroportXastroToken = __assign(__assign(__assign({}, _18), _19), _20);
    contracts.AstroportRouter = __assign(__assign(__assign({}, _21), _22), _23);
    contracts.AstroportWhitelist = __assign(__assign(__assign({}, _24), _25), _26);
    contracts.AstroportGenerator = __assign(__assign(__assign({}, _27), _28), _29);
    contracts.AstroportVesting = __assign(__assign(__assign({}, _30), _31), _32);
    contracts.AstroportMaker = __assign(__assign(__assign({}, _33), _34), _35);
    contracts.AstroportOracle = __assign(__assign(__assign({}, _36), _37), _38);
})(contracts = exports.contracts || (exports.contracts = {}));
