/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.24.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/
import * as _1 from "./AstroportFactory.client";
import * as _2 from "./AstroportFactory.message-composer";
import * as _4 from "./AstroportPair.client";
import * as _5 from "./AstroportPair.message-composer";
import * as _7 from "./AstroportToken.client";
import * as _8 from "./AstroportToken.message-composer";
import * as _10 from "./AstroportPairStable.client";
import * as _11 from "./AstroportPairStable.message-composer";
import * as _13 from "./AstroportPairAstroXastro.client";
import * as _14 from "./AstroportPairAstroXastro.message-composer";
import * as _16 from "./AstroportStaking.client";
import * as _17 from "./AstroportStaking.message-composer";
import * as _19 from "./AstroportXastroToken.client";
import * as _20 from "./AstroportXastroToken.message-composer";
import * as _22 from "./AstroportRouter.client";
import * as _23 from "./AstroportRouter.message-composer";
import * as _25 from "./AstroportWhitelist.client";
import * as _26 from "./AstroportWhitelist.message-composer";
import * as _28 from "./AstroportGenerator.client";
import * as _29 from "./AstroportGenerator.message-composer";
import * as _31 from "./AstroportVesting.client";
import * as _32 from "./AstroportVesting.message-composer";
import * as _34 from "./AstroportMaker.client";
import * as _35 from "./AstroportMaker.message-composer";
import * as _37 from "./AstroportOracle.client";
import * as _38 from "./AstroportOracle.message-composer";
export declare namespace contracts {
    const AstroportFactory: {
        AstroportFactoryMessageComposer: typeof _2.AstroportFactoryMessageComposer;
        AstroportFactoryQueryClient: typeof _1.AstroportFactoryQueryClient;
        AstroportFactoryClient: typeof _1.AstroportFactoryClient;
    };
    const AstroportPair: {
        AstroportPairMessageComposer: typeof _5.AstroportPairMessageComposer;
        AstroportPairQueryClient: typeof _4.AstroportPairQueryClient;
        AstroportPairClient: typeof _4.AstroportPairClient;
    };
    const AstroportToken: {
        AstroportTokenMessageComposer: typeof _8.AstroportTokenMessageComposer;
        AstroportTokenQueryClient: typeof _7.AstroportTokenQueryClient;
        AstroportTokenClient: typeof _7.AstroportTokenClient;
    };
    const AstroportPairStable: {
        AstroportPairStableMessageComposer: typeof _11.AstroportPairStableMessageComposer;
        AstroportPairStableQueryClient: typeof _10.AstroportPairStableQueryClient;
        AstroportPairStableClient: typeof _10.AstroportPairStableClient;
    };
    const AstroportPairAstroXastro: {
        AstroportPairAstroXastroMessageComposer: typeof _14.AstroportPairAstroXastroMessageComposer;
        AstroportPairAstroXastroQueryClient: typeof _13.AstroportPairAstroXastroQueryClient;
        AstroportPairAstroXastroClient: typeof _13.AstroportPairAstroXastroClient;
    };
    const AstroportStaking: {
        AstroportStakingMessageComposer: typeof _17.AstroportStakingMessageComposer;
        AstroportStakingQueryClient: typeof _16.AstroportStakingQueryClient;
        AstroportStakingClient: typeof _16.AstroportStakingClient;
    };
    const AstroportXastroToken: {
        AstroportXastroTokenMessageComposer: typeof _20.AstroportXastroTokenMessageComposer;
        AstroportXastroTokenQueryClient: typeof _19.AstroportXastroTokenQueryClient;
        AstroportXastroTokenClient: typeof _19.AstroportXastroTokenClient;
    };
    const AstroportRouter: {
        AstroportRouterMessageComposer: typeof _23.AstroportRouterMessageComposer;
        AstroportRouterQueryClient: typeof _22.AstroportRouterQueryClient;
        AstroportRouterClient: typeof _22.AstroportRouterClient;
    };
    const AstroportWhitelist: {
        AstroportWhitelistMessageComposer: typeof _26.AstroportWhitelistMessageComposer;
        AstroportWhitelistQueryClient: typeof _25.AstroportWhitelistQueryClient;
        AstroportWhitelistClient: typeof _25.AstroportWhitelistClient;
    };
    const AstroportGenerator: {
        AstroportGeneratorMessageComposer: typeof _29.AstroportGeneratorMessageComposer;
        AstroportGeneratorQueryClient: typeof _28.AstroportGeneratorQueryClient;
        AstroportGeneratorClient: typeof _28.AstroportGeneratorClient;
    };
    const AstroportVesting: {
        AstroportVestingMessageComposer: typeof _32.AstroportVestingMessageComposer;
        AstroportVestingQueryClient: typeof _31.AstroportVestingQueryClient;
        AstroportVestingClient: typeof _31.AstroportVestingClient;
    };
    const AstroportMaker: {
        AstroportMakerMessageComposer: typeof _35.AstroportMakerMessageComposer;
        AstroportMakerQueryClient: typeof _34.AstroportMakerQueryClient;
        AstroportMakerClient: typeof _34.AstroportMakerClient;
    };
    const AstroportOracle: {
        AstroportOracleMessageComposer: typeof _38.AstroportOracleMessageComposer;
        AstroportOracleQueryClient: typeof _37.AstroportOracleQueryClient;
        AstroportOracleClient: typeof _37.AstroportOracleClient;
    };
}
